name: testing_process
on: 
  push:
    branches: main
jobs:
  test:
      runs-on: ubuntu-latest

      steps:
        name: check dir
        uses: checkout repository@v4

        name: install dependencies
        run: python -m pip install -r requirements.txt

        name: testing
        run: python unittest action_test\test_calculator.py 



